default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: talky_development

test:
  <<: *default
  database: talky_test

production:
  <<: *default
  database: talky_production
